# Generated by Django 3.2.7 on 2021-09-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationrefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('targetcomponentid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'associationrefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributevaluerefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('valueid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'attributevaluerefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('conceptid', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexmaprefsetF',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('mapgroup', models.SmallIntegerField(db_column='mapGroup')),
                ('mappriority', models.SmallIntegerField(db_column='mapPriority')),
                ('maprule', models.TextField(blank=True, db_column='mapRule', null=True)),
                ('mapadvice', models.TextField(blank=True, db_column='mapAdvice', null=True)),
                ('maptarget', models.CharField(blank=True, db_column='mapTarget', max_length=18, null=True)),
                ('correlationid', models.CharField(db_column='correlationId', max_length=18)),
            ],
            options={
                'db_table': 'complexmaprefset_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptFinisheds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=191)),
                ('user_id', models.IntegerField()),
                ('conceptid', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept_finisheds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptS',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('definitionstatusid', models.CharField(max_length=18)),
                ('category_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionS',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('conceptid', models.CharField(max_length=18)),
                ('languagecode', models.CharField(max_length=2)),
                ('typeid', models.CharField(max_length=18)),
                ('term', models.CharField(max_length=255)),
                ('casesignificanceid', models.CharField(max_length=18)),
                ('category_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'description_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedmaprefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('mapgroup', models.SmallIntegerField(db_column='mapGroup')),
                ('mappriority', models.SmallIntegerField(db_column='mapPriority')),
                ('maprule', models.TextField(blank=True, db_column='mapRule', null=True)),
                ('mapadvice', models.TextField(blank=True, db_column='mapAdvice', null=True)),
                ('maptarget', models.CharField(blank=True, db_column='mapTarget', max_length=18, null=True)),
                ('correlationid', models.CharField(db_column='correlationId', max_length=18)),
                ('mapcategoryid', models.CharField(blank=True, db_column='mapCategoryId', max_length=18, null=True)),
            ],
            options={
                'db_table': 'extendedmaprefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=191, unique=True)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'failed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangrefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('acceptabilityid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'langrefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoincEspaña',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=176)),
                ('prop', models.CharField(max_length=50)),
                ('time_aspct', models.CharField(max_length=41)),
                ('system', models.CharField(max_length=117)),
                ('scale_typ', models.CharField(max_length=20)),
                ('method_typ', models.CharField(max_length=142)),
                ('cla', models.CharField(max_length=64)),
                ('shortname', models.CharField(max_length=9)),
                ('long_common_name', models.CharField(max_length=100)),
                ('relatednames2', models.CharField(max_length=182)),
                ('LinguisticVariantDisplayName', models.CharField(max_length=28)),
            ],
            options={
                'db_table': 'loinc_españa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=191)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OwlexpressionS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('owlexpression', models.TextField(db_column='owlExpression')),
            ],
            options={
                'db_table': 'owlexpression_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=191)),
                ('token', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipS',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('sourceid', models.CharField(max_length=18)),
                ('destinationid', models.CharField(max_length=18)),
                ('relationshipgroup', models.CharField(max_length=18)),
                ('typeid', models.CharField(max_length=18)),
                ('characteristictypeid', models.CharField(max_length=18)),
                ('modifierid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'relationship_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimplemaprefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
                ('maptarget', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'simplemaprefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimplerefsetS',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('refsetid', models.CharField(max_length=18)),
                ('referencedcomponentid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'simplerefset_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatedRelationshipS',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('sourceid', models.CharField(max_length=18)),
                ('destinationid', models.CharField(max_length=18)),
                ('relationshipgroup', models.CharField(max_length=18)),
                ('typeid', models.CharField(max_length=18)),
                ('characteristictypeid', models.CharField(max_length=18)),
                ('modifierid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'stated_relationship_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256)),
                ('conceptid', models.CharField(max_length=18)),
                ('delete', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'synonyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SynonymsUpdates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('synonym_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('update', models.CharField(max_length=191)),
                ('old_value', models.CharField(max_length=191)),
                ('new_value', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'synonyms_updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SynonymVotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=191)),
                ('user_id', models.IntegerField()),
                ('synonym_id', models.CharField(max_length=191)),
                ('like', models.IntegerField(blank=True, null=True)),
                ('dislike', models.IntegerField(blank=True, null=True)),
                ('delete', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'synonym_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextdefinitionS',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effectivetime', models.CharField(max_length=8)),
                ('active', models.CharField(max_length=1)),
                ('moduleid', models.CharField(max_length=18)),
                ('conceptid', models.CharField(max_length=18)),
                ('languagecode', models.CharField(max_length=2)),
                ('typeid', models.CharField(max_length=18)),
                ('term', models.CharField(max_length=4096)),
                ('casesignificanceid', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'textdefinition_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'type_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('apellido_p', models.CharField(max_length=191)),
                ('apellido_m', models.CharField(max_length=191)),
                ('curp', models.CharField(blank=True, max_length=191, null=True)),
                ('birtdate', models.DateTimeField()),
                ('born_state', models.CharField(max_length=191)),
                ('born_city', models.CharField(max_length=191)),
                ('hospital_institution', models.CharField(max_length=191)),
                ('cedula', models.CharField(blank=True, max_length=191, null=True)),
                ('position', models.CharField(max_length=191)),
                ('last_degree', models.CharField(max_length=191)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=191)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('delete', models.IntegerField()),
                ('rol_id', models.IntegerField()),
                ('email_validation_token', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptosNoEncontrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
