# Generated by Django 3.2.7 on 2021-10-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoincEspaña',
        ),
    ]
